spring.application.name=solar-watch

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/solarwatch?sslmode=disable
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

codecool.app.jwtSecret=kQX5seyAhUy3z7G8OsZiJV8XdeFifA7q85LJyLXxi54=
codecool.app.jwtExpirationMs=86400000

codecool.app.admin-password=admin