spring.application.name=solar-watch

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/solarwatch?sslmode=disable
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

codecool.app.jwtSecret=${SOLARWATCH_JWT_SECRET}
codecool.app.jwtExpirationMs=${SOLARWATCH_JWT_EXPIRATION}

codecool.app.admin-password=admin